return {
	"nvim-treesitter/nvim-treesitter",
	branch = "master",
	build = ":TSUpdate",
	-- Not lazy: telescope's previewer asks for a highlights query the moment you
	-- open live_grep, so the queries have to be on the runtimepath already.
	-- Lazy-loading on BufReadPost would leave the first preview unhighlighted.
	lazy = false,
	opts = {
		ensure_installed = {
			"rust",
			"python",
			"c",
			"cpp",
			"lua",
			"toml",
			"yaml",
			"json",
			"markdown",
			"markdown_inline",
			"bash",
			"diff",
			"gitcommit",
			"query",
			"vim",
			"vimdoc",
		},
		highlight = {
			enable = true,
			-- Vim's regex syntax alongside treesitter is mostly redundant and
			-- slows down big files.
			additional_vim_regex_highlighting = false,
		},
		indent = { enable = true },
	},
	config = function(_, opts)
		-- A few grammars (swift among them) ship no pre-generated parser.c and
		-- must be built with `tree-sitter generate`. nvim-treesitter master still
		-- passes --no-bindings, which tree-sitter CLI 0.25 removed (bindings are
		-- no longer generated by default), so those installs fail with
		--   tip: to pass '--no-bindings' as a value, use '-- --no-bindings'
		-- Presetting ts_generate_args skips install.lua's lazy default, which is
		-- where the stale flag comes from.
		require("nvim-treesitter.install").ts_generate_args =
			{ "generate", "--abi", tostring(vim.treesitter.language_version) }

		require("nvim-treesitter.configs").setup(opts)
	end,
}
